application: bilentapptest
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: webob
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest

handlers:
- url: /sys/.*
  script: main.app
  login: admin

- url: /_ah/.*
  script: main.sys

- url: /api/.*
  script: main.app
  secure: optional

- url: /bkend/.*
  script: main.app
  secure: optional

- url: /auth/.*
  script: main.app
  secure: optional

- url: /images
  static_dir: www/app/images

- url: /scripts
  static_dir: www/app/scripts

- url: /elements
  static_dir: www/app/elements

- url: /styles
  static_dir: www/app/styles

- url: /bower_components
  static_dir: www/bower_components

- url: /
  static_files: www/app/index.html
  upload: www/app/index.html

- url: /sys.html
  static_files: www/app/sys.html
  upload: www/app/sys.html
  login: admin

- url: .*
  static_dir: www/app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*/less/.*
- ^(.*/)?tools/.*
- ^(.*/)?.data/.*
- ^(.*/)?.git/.*
- ^(.*/)?tests/.*
- ^(.*/)?node_modules/.*
- ^(.*/)?Gemfile.*
- ^(.*/)?Guardfile.*
- ^(.*/)?.*/plupload/.*/.*
- ^(.*/)?microsites/app/.*
- ^(.*/)?microsites/.tmp/.*
- ^(.*/)?microsites/docs/.*
- ^(.*/)?microsites/node_modules/.*
- ^(.*/)?microsites/\..*
- ^(.*/)?microsites/.*\.md
- ^(.*/)?microsites/.*\.json
- ^(.*/)?microsites/LICENSE
