application: bilent-apps
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: webob
  version: latest
- name: webapp2
  version: latest
- name: pycrypto
  version: latest

handlers:
- url: /sys/.*
  script: main.app
  login: admin

- url: /_ah/.*
  script: main.sys

- url: /api/.*
  script: main.app
  secure: optional

- url: /bkend/.*
  script: main.app
  secure: optional

- url: /auth/.*
  script: main.app
  secure: optional

- url: /
  static_files: www/dist/index.html
  upload: www/dist/index.html

- url: /sys.html
  static_files: www/dist/sys.html
  upload: www/dist/sys.html
  login: admin

- url: /
  static_dir: www/dist/

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*/less/.*
- ^(.*/)?tools/.*
- ^(.*/)?.data/.*
- ^(.*/)?.git/.*
- ^(.*/)?tests/.*
- ^(.*/)?node_modules/.*
- ^(.*/)?Gemfile.*
- ^(.*/)?Guardfile.*
- ^(.*/)?.*/plupload/.*/.*
- ^(.*/)?www/app/.*
- ^(.*/)?www/.tmp/.*
- ^(.*/)?www/bower_components/.*
- ^(.*/)?www/node_modules/.*
- ^(.*/)?www/\..*
- ^(.*/)?www/.*\.md
- ^(.*/)?www/dist/bower_components/((?!webcomponentsjs\/webcomponents\-lite\.min).)*\..*
- ^(.*/)?www/dist/bower_components/.*(LICENSE|COPYING|Makefile|marked)
- ^(.*/)?www/[^/]*\.js
- ^(.*/)?www/.*\.json
