'''
   KyashMerchantAPILib
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2015
'''
from datetime import datetime
from pykyash.Models.KyashObject import KyashObject


class Cancel(KyashObject):
    schema = {
        'cancelled_at': datetime,
        'reason': str,
        'should_refund': bool,
        'refunded': bool,
        'refund_amount': float,
        'refund_charges': float,
        'charge_paid_by': str,
    }