'''
   KyashMerchantAPILib
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2015
'''
from pykyash.Models.KyashObject import KyashObject


class Fee(KyashObject):
    schema = {
        'amount': float,
        'description': unicode,
        'rule': unicode,
        'charged_by': str
    }
