'''
   KyashMerchantAPILib
 
   This file was automatically generated by APIMATIC BETA v2.0 on 02/08/2015
'''
from pykyash.Models.KyashObject import KyashObject


class KyashError(KyashObject, Exception):
    schema = {
        'code': int,
        'status': str,
        'message': unicode
    }

    def __str__(self):
        return self.message
